In [67]:
# Import Pandas and Numpy libraries.
import pandas as pd
import numpy as np

In [68]:
# Load actual_duration.csv file.
actual_duration = pd.read_csv('actual_duration.csv')

actual_duration

,sub_icb_location_code,sub_icb_location_ons_code,sub_icb_location_name,icb_ons_code,region_ons_code,appointment_date,actual_duration,count_of_appointments
0,00L,E38000130,NHS North East and North Cumbria ICB - 00L,E54000050,E40000012,01-Dec-21,31-60 Minutes,364
1,00L,E38000130,NHS North East and North Cumbria ICB - 00L,E54000050,E40000012,01-Dec-21,21-30 Minutes,619
2,00L,E38000130,NHS North East and North Cumbria ICB - 00L,E54000050,E40000012,01-Dec-21,6-10 Minutes,1698
3,00L,E38000130,NHS North East and North Cumbria ICB - 00L,E54000050,E40000012,01-Dec-21,Unknown / Data Quality,1277
4,00L,E38000130,NHS North East and North Cumbria ICB - 00L,E54000050,E40000012,01-Dec-21,16-20 Minutes,730
...,...,...,...,...,...,...,...,...
137788,X2C4Y,E38000254,NHS West Yorkshire ICB - X2C4Y,E54000054,E40000012,30-Jun-22,31-60 Minutes,430
137789,X2C4Y,E38000254,NHS West Yorkshire ICB - X2C4Y,E54000054,E40000012,30-Jun-22,21-30 Minutes,751
137790,X2C4Y,E38000254,NHS West Yorkshire ICB - X2C4Y,E54000054,E40000012,30-Jun-22,16-20 Minutes,921
137791,X2C4Y,E38000254,NHS West Yorkshire ICB - X2C4Y,E54000054,E40000012,30-Jun-22,11-15 Minutes,1439
137792,X2C4Y,E38000254,NHS West Yorkshire ICB - X2C4Y,E54000054,E40000012,30-Jun-22,1-5 Minutes,1739

In [69]:
# Sense-check the actual_duration DataFrame.
print('Shape:\n', actual_duration.shape)
print('\nColumns names:\n', actual_duration.columns)
print('\nColumns types:\n', actual_duration.dtypes)
print('\nSum of missing values:\n', actual_duration.isnull().sum())

Shape:
 (137793, 8)

Columns names:
 Index(['sub_icb_location_code', 'sub_icb_location_ons_code',
       'sub_icb_location_name', 'icb_ons_code', 'region_ons_code',
       'appointment_date', 'actual_duration', 'count_of_appointments'],
      dtype='object')

Columns types:
 sub_icb_location_code        object
sub_icb_location_ons_code    object
sub_icb_location_name        object
icb_ons_code                 object
region_ons_code              object
appointment_date             object
actual_duration              object
count_of_appointments         int64
dtype: object

Sum of missing values:
 sub_icb_location_code        0
sub_icb_location_ons_code    0
sub_icb_location_name        0
icb_ons_code                 0
region_ons_code              0
appointment_date             0
actual_duration              0
count_of_appointments        0
dtype: int64

In [70]:
# Metadata and descriptive statistics of the actual_duration DataFrame.
print(actual_duration.info())
print('\nDescriptive statistics:\n', actual_duration.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137793 entries, 0 to 137792
Data columns (total 8 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   sub_icb_location_code      137793 non-null  object
 1   sub_icb_location_ons_code  137793 non-null  object
 2   sub_icb_location_name      137793 non-null  object
 3   icb_ons_code               137793 non-null  object
 4   region_ons_code            137793 non-null  object
 5   appointment_date           137793 non-null  object
 6   actual_duration            137793 non-null  object
 7   count_of_appointments      137793 non-null  int64
dtypes: int64(1), object(7)
memory usage: 8.4+ MB
None

Descriptive statistics:
        count_of_appointments
count          137793.000000
mean             1219.080011
std              1546.902956
min                 1.000000
25%               194.000000
50%               696.000000
75%              1621.000000
max             15400.000000

In [71]:
# Load appointments_regional.csv file.
appointments_regional = pd.read_csv('appointments_regional.csv')

appointments_regional

,icb_ons_code,appointment_month,appointment_status,hcp_type,appointment_mode,time_between_book_and_appointment,count_of_appointments
0,E54000034,2020-01,Attended,GP,Face-to-Face,1 Day,8107
1,E54000034,2020-01,Attended,GP,Face-to-Face,15 to 21 Days,6791
2,E54000034,2020-01,Attended,GP,Face-to-Face,2 to 7 Days,20686
3,E54000034,2020-01,Attended,GP,Face-to-Face,22 to 28 Days,4268
4,E54000034,2020-01,Attended,GP,Face-to-Face,8 to 14 Days,11971
...,...,...,...,...,...,...,...
596816,E54000050,2022-06,Unknown,Unknown,Unknown,2 to 7 Days,21
596817,E54000050,2022-06,Unknown,Unknown,Unknown,22 to 28 Days,8
596818,E54000050,2022-06,Unknown,Unknown,Unknown,8 to 14 Days,28
596819,E54000050,2022-06,Unknown,Unknown,Unknown,More than 28 Days,17
596820,E54000050,2022-06,Unknown,Unknown,Unknown,Same Day,10

In [72]:
# Sense-check the appointments_regional DataFrame.
print('Shape:\n', appointments_regional.shape)
print('\nColumns names:\n', appointments_regional.columns)
print('\nColumns types:\n', appointments_regional.dtypes)
print('\nSum of missing values:\n', appointments_regional.isnull().sum())

Shape:
 (596821, 7)

Columns names:
 Index(['icb_ons_code', 'appointment_month', 'appointment_status', 'hcp_type',
       'appointment_mode', 'time_between_book_and_appointment',
       'count_of_appointments'],
      dtype='object')

Columns types:
 icb_ons_code                         object
appointment_month                    object
appointment_status                   object
hcp_type                             object
appointment_mode                     object
time_between_book_and_appointment    object
count_of_appointments                 int64
dtype: object

Sum of missing values:
 icb_ons_code                         0
appointment_month                    0
appointment_status                   0
hcp_type                             0
appointment_mode                     0
time_between_book_and_appointment    0
count_of_appointments                0
dtype: int64

In [73]:
# Metadata and descriptive statistics of the appointments_regional DataFrame.
print(appointments_regional.info())
print('\nDescriptive statistics:\n', appointments_regional.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 596821 entries, 0 to 596820
Data columns (total 7 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   icb_ons_code                       596821 non-null  object
 1   appointment_month                  596821 non-null  object
 2   appointment_status                 596821 non-null  object
 3   hcp_type                           596821 non-null  object
 4   appointment_mode                   596821 non-null  object
 5   time_between_book_and_appointment  596821 non-null  object
 6   count_of_appointments              596821 non-null  int64
dtypes: int64(1), object(6)
memory usage: 31.9+ MB
None

Descriptive statistics:
        count_of_appointments
count          596821.000000
mean             1244.601857
std              5856.887042
min                 1.000000
25%                 7.000000
50%                47.000000
75%               308.000000
max            211265.000000

In [74]:
# Load national_categories.xlsx file.
national_categories = pd.read_excel('national_categories.xlsx')

national_categories

,appointment_date,icb_ons_code,sub_icb_location_name,service_setting,context_type,national_category,count_of_appointments,appointment_month
0,2021-08-02,E54000050,NHS North East and North Cumbria ICB - 00L,Primary Care Network,Care Related Encounter,Patient contact during Care Home Round,3,2021-08
1,2021-08-02,E54000050,NHS North East and North Cumbria ICB - 00L,Other,Care Related Encounter,Planned Clinics,7,2021-08
2,2021-08-02,E54000050,NHS North East and North Cumbria ICB - 00L,General Practice,Care Related Encounter,Home Visit,79,2021-08
3,2021-08-02,E54000050,NHS North East and North Cumbria ICB - 00L,General Practice,Care Related Encounter,General Consultation Acute,725,2021-08
4,2021-08-02,E54000050,NHS North East and North Cumbria ICB - 00L,General Practice,Care Related Encounter,Structured Medication Review,2,2021-08
...,...,...,...,...,...,...,...,...
817389,2022-06-30,E54000054,NHS West Yorkshire ICB - X2C4Y,Extended Access Provision,Care Related Encounter,Unplanned Clinical Activity,12,2022-06
817390,2022-06-30,E54000054,NHS West Yorkshire ICB - X2C4Y,Extended Access Provision,Care Related Encounter,Planned Clinics,4,2022-06
817391,2022-06-30,E54000054,NHS West Yorkshire ICB - X2C4Y,Extended Access Provision,Care Related Encounter,Planned Clinical Procedure,92,2022-06
817392,2022-06-30,E54000054,NHS West Yorkshire ICB - X2C4Y,Extended Access Provision,Care Related Encounter,General Consultation Routine,4,2022-06
817393,2022-06-30,E54000054,NHS West Yorkshire ICB - X2C4Y,Extended Access Provision,Care Related Encounter,General Consultation Acute,19,2022-06

In [75]:
# Sense-check the national_categories DataFrame.
print('Shape:\n', national_categories.shape)
print('\nColumns names:\n', national_categories.columns)
print('\nColumns types:\n', national_categories.dtypes)
print('\nSum of missing values:\n', national_categories.isnull().sum())

Shape:
 (817394, 8)

Columns names:
 Index(['appointment_date', 'icb_ons_code', 'sub_icb_location_name',
       'service_setting', 'context_type', 'national_category',
       'count_of_appointments', 'appointment_month'],
      dtype='object')

Columns types:
 appointment_date         datetime64[ns]
icb_ons_code                     object
sub_icb_location_name            object
service_setting                  object
context_type                     object
national_category                object
count_of_appointments             int64
appointment_month                object
dtype: object

Sum of missing values:
 appointment_date         0
icb_ons_code             0
sub_icb_location_name    0
service_setting          0
context_type             0
national_category        0
count_of_appointments    0
appointment_month        0
dtype: int64

In [76]:
# Metadata and descriptive statistics of the national_categories DataFrame.
print(national_categories.info())
print('\nDescriptive statistics:\n', national_categories.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 817394 entries, 0 to 817393
Data columns (total 8 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   appointment_date       817394 non-null  datetime64[ns]
 1   icb_ons_code           817394 non-null  object
 2   sub_icb_location_name  817394 non-null  object
 3   service_setting        817394 non-null  object
 4   context_type           817394 non-null  object
 5   national_category      817394 non-null  object
 6   count_of_appointments  817394 non-null  int64
 7   appointment_month      817394 non-null  object
dtypes: datetime64[ns](1), int64(1), object(6)
memory usage: 49.9+ MB
None

Descriptive statistics:
        count_of_appointments
count          817394.000000
mean              362.183684
std              1084.576600
min                 1.000000
25%                 7.000000
50%                25.000000
75%               128.000000
max             16590.000000

In [97]:
# How many locations are there in the data set?
print('Count of locations by location name: ', len(national_categories[
    'sub_icb_location_name'].unique()))
print('Count of locations by organisation code: ', len(national_categories[
    'icb_ons_code'].unique()))

Count of locations by location name:  106
Count of locations by organisation code:  42

In [86]:
# Five locations (by location name) with the highest number of records.
national_categories1 = national_categories['sub_icb_location_name'
    ].value_counts().reset_index(name='count_of_appointments')

national_categories1.head()

                                         index  count_of_appointments
0            NHS North West London ICB - W2U3Z                  13007
1                NHS Kent and Medway ICB - 91Q                  12637
2                          NHS Devon ICB - 15N                  12526
3  NHS Hampshire and Isle Of Wight ICB - D9Y0V                  12171
4            NHS North East London ICB - A3A8R                  11837

In [96]:
# Number of service settings, context types, national categories, and appointment statuses.
print('Total number of service settings: ', national_categories['service_setting'].count())
print('Number of service settings by cattegory: \n', national_categories['service_setting'
                                                                        ].value_counts())

print('\nTotal number of context types: ', national_categories['context_type'].count())
print('Number of context types by cattegory: \n', national_categories['context_type'
                                                                        ].value_counts())

print('\nTotal number of national categories: ', national_categories['national_category'
                                                                    ].count())
print('Number of national categories by cattegory: \n', national_categories[
                                                                        'national_category'
                                                                        ].value_counts())

print('\nTotal number of appointment statuses: ', appointments_regional['appointment_status'
                                                                       ].count())
print('Number of appointment statuses by cattegory: \n', appointments_regional[
                                                                        'appointment_status'
                                                                        ].value_counts())

Total number of service settings:  817394
Number of service settings by cattegory:
 General Practice             359274
Primary Care Network         183790
Other                        138789
Extended Access Provision    108122
Unmapped                      27419
Name: service_setting, dtype: int64

Total number of context types:  817394
Number of context types by cattegory:
 Care Related Encounter    700481
Inconsistent Mapping       89494
Unmapped                   27419
Name: context_type, dtype: int64

Total number of national categories:  817394
Number of national categories by cattegory:
 Inconsistent Mapping                                                   89494
General Consultation Routine                                           89329
General Consultation Acute                                             84874
Planned Clinics                                                        76429
Clinical Triage                                                        74539
Planned Clinical Procedure                                             59631
Structured Medication Review                                           44467
Service provided by organisation external to the practice              43095
Home Visit                                                             41850
Unplanned Clinical Activity                                            40415
Patient contact during Care Home Round                                 28795
Unmapped                                                               27419
Care Home Visit                                                        26644
Social Prescribing Service                                             26492
Care Home Needs Assessment & Personalised Care and Support Planning    23505
Non-contractual chargeable work                                        20896
Walk-in                                                                14179
Group Consultation and Group Education                                  5341
Name: national_category, dtype: int64

Total number of appointment statuses:  596821
Number of appointment statuses by cattegory:
 Attended    232137
Unknown     201324
DNA         163360
Name: appointment_status, dtype: int64